services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /media/main-drive/home-services/Calibre/config:/config
      - /media/main-drive/home-data/Books/Books:/books
    ports:
      - 8083:8083
    restart: always

