services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat
    environment:
      # Set the timezone to your local timezone
      - TZ=America/New_York
    ports:
      - '8945:8945'
    volumes:
      - ${PINCHFLAT_CONFIG}:/config
      - ${PINCHFLAT_DOWNLOADS}:/downloads
    network_mode: bridge
