services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat
    environment:
      # Set the timezone to your local timezone
      - TZ=Europe/Berlin
    ports:
      - '8945:8945'
    volumes:
      - ${PINCHFLAT_CONFIG}:/config
      - ${PINCHFLAT_DOWNLOADS}:/downloads
    network_mode: bridge
    dns:
      - 8.8.8.8
      - 8.8.4.4
